apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-12-10T05:58:26Z"
  generation: 1
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: ajayondocker/mmv3-currency-conversion-service:0.0.14-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv3-currency-conversion-service
        envFrom:
          - configMapRef:
              name: currency-conversion
#        env:
#        - name: CURRENCY_EXCHANGE_URI
#          value: http://currency-exchange
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-10T05:58:37Z"
    lastUpdateTime: "2024-12-10T05:58:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-10T05:58:26Z"
    lastUpdateTime: "2024-12-10T05:58:37Z"
    message: ReplicaSet "currency-conversion-6fd7f76686" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-12-10T06:04:35Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.234.110
  clusterIPs:
  - 34.118.234.110
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30468
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.29.123.38
      ipMode: VIP
---
apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default
